### ISSUE TITLE
Login feature

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#1]

**Comment by zach27** [comment]
**Assignments:**
* Abhi: view and routers
* Zach: controller and model

**Comment by zach27** [comment]
@abjay, what do you want to name your view for the login page (right now it is `helloworld`)? Since the same view will be used for register as well, we probably shouldn't name it `login`. Our requirements calls this page the `intro` page, but I'm not sure if `intro` is self-explanatory. Do you have a better idea? I'll need to know the name so I can render it in my code.

**Comment by zach27** [comment]
Also, we'll need to create some sort of welcome view (empty at this point) to direct the user to upon logging in.

**Comment by abjay** [comment]
I think we should keep it consistent with the requirements and name it _intro_. Or we could name it _main_page_ or _main_ and change it in the requirements document. Let me know which one you pick

**Comment by zach27** [comment]
I like `intro` for now. If we want, we can change it later I suppose.

**Comment by abjay** [comment]
Yes, we will work on that. Do you want to add that feature into this sprint or move it to a future sprint?

**Comment by abjay** [comment]
Okay sounds good!

**Comment by abjay** [comment]
I was mentioning about the _user home page_ feature. Do you think we should add it onto this sprint or move it to a future sprint?

**Comment by zach27** [comment]
I think it needs to be this sprint since our requirements specify that we will direct users to a page with "Welcome!" displayed. This will need to be a different view. You could name this `home` or similar. For now it will be mostly empty (no drips). In later sprints we'll fix that.

**Comment by abjay** [comment]
Yes, that's a good idea!

**Comment by zach27** [comment]
I've done some work but have to stop for now. When you finish your view and router, we'll be able to test it out. I'm not sure if the sessions will work right now -- I'll need to make some changes to the controller.

**Comment by abjay** [comment]
Okay. I've to stop for a bit too. I'll let you know once I've pushed the
view

**Comment by zach27** [comment]
As discussed, let's forget about the `connect-flash` middleware for now. Instead, for the message, just render the view and send along any data message as a JSON object.

**Comment by zach27** [comment]
Login feature implemented and tested.
