### ISSUE TITLE
Move metric overviews/definitions up to the `docs` directory

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#15]
This info belongs one level up, not in `sprint1` where it currently resides. Metric _measurements_ should remain in their respective sprint directories.

**Comment by zach27** [comment]
I've moved these up to the `metric-definitions` directory. Still, we should remove the definitions from the sprint 1 documents to prevent duplicate information. In their place, we can just link to the respective metric definition, as I've done here: https://github.com/CS506/fall2016-group1/blob/master/docs/sprint1/requirements-testability-measurements.md

**Comment by ShermantheCreator** [comment]
I went through and revised the documents in sprint 1 to link to their definitions and deleting the actual definitions from the documents. We can close this issue if you are satisfied with the documents.

**Comment by zach27** [comment]
@ShermantheCreator thanks. I can check this later, but feel free to close this issue since you did the work.
