### ISSUE TITLE
Sprint 2 requirements metric measurements

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#18]
As discussed today, let's finish our metric measurements on the requirements by the end of the day, Thursday, November 17, and have them posted to the `sprint2` directory.

**Comment by ShermantheCreator** [comment]
Zach, I have reviewed the baselined requirements for Sprint 2. I agree with your comments on my section, I deleted the part pertaining to the buckets in the data requirements. Also, I believe I completed the schema section. Let me know if you see any additional things I might have missed.

**Comment by ShermantheCreator** [comment]
Also, in regards to your comments on the bucket list section, about the refresh every 5 seconds. I think this can be moved to a later sprint, as for now we won't have a need for it in this sprint.

**Comment by zach27** [comment]
@ShermantheCreator, I've moved the auto-refresh feature to the backlog.

**Comment by ShermantheCreator** [comment]
@zach27 @abjay One thing I noticed is we all have a different number of detailed requirements. Zach had 29, Abhi 30, and I had 31. We should probably settle on one to show some unification in our measurements. It looks like the differences are in the Data Requirements section, specifically 4.1 .

**Comment by zach27** [comment]
@ShermantheCreator Yes, I made a footnote about the actual number in my document. I thought some of the points in the data requirements were more for grouping and not really independent requirements. Let's agree on which requirements to use.

**Comment by ShermantheCreator** [comment]
We have agreed that detailed requirements can fluctuate between the different measurements.
