### ISSUE TITLE
Spaces in Name field to Register

### ISSUE THREAD

**Issue by ShermantheCreator** [CS506/fall2016-group1#22]
Add the ability to have whitespace in the Name field of the Register portion of the intro page. 

This can be done by making revisions in the intro view document.

**Comment by zach27** [comment]
Guys, after thinking about this, I'm wondering if we should just leave off validation for the `name` field. After all, our sprint 1 requirements do not specify any kind restriction on the `name` field. Some names contain punctuation, anyway. What do you think? We could just do length checking, as specified in the requirements.

**Comment by ShermantheCreator** [comment]
Zach, I think this is actually the most logical decision at this point. Let's keep the length restrictions, but not have any checking on the characters.

**Comment by zach27** [comment]
I've fixed this bug in the `bugs` branch.
