### ISSUE TITLE
Choice of anonymity

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#30]

**Comment by raghav4494** [comment]
Design part is finished. Once it is reviewed, we can start measuring and head implementation phase.

**Comment by zach27** [comment]
@raghav4494 @ashishkchaturvedi As you probably guessed, you'll need to modify the "display drips" functionality (probably in the view) to print the user along with the drip ***only if the drip is not anonymous***.

**Comment by raghav4494** [comment]
I have changed the attribute property of anonymity to be Boolean and have uploaded the latest code in the repo.

**Comment by zach27** [comment]
Guys, whoever finished this feature can close this, correct?

**Comment by raghav4494** [comment]
I think all the features posted in the requirements are covered. When running the programs, Build passed successfully and there is good coverage. So, I am closing the issue.
