### ISSUE TITLE
User not redirected to home page from intro page if logged in

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#33]
Need to debug this further. Doesn't seem to happen all the time.

**Comment by abjay** [comment]
Is this bug caused when the user is logging in, or when the user is already logged in - visits some other page - and then tries to access back the home page?

**Comment by zach27** [comment]
It happens when the user is already logged in and goes back to the home page.

**Comment by abjay** [comment]
Okay, I see that you've mentioned that it doesn't seem to happen all the time. We need to list the scenarios when it does happen. We can discuss about this further in the meeting.

**Comment by zach27** [comment]
Ok, I can look into it further today.

**Comment by zach27** [comment]
I've fixed this bug and created test cases for it.
