### ISSUE TITLE
Decide name for "creating an account" feature

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#4]
Guys, can we choose a name for the feature that allows a user to create an account? Right now, it looks like we have several names in use:

* Account creation
* Sign-up
* Sign-in

Let's choose a name and be consistent. When I hear *sign-in*, I typically think login, not creating an account, so let's steer away from that one. Another option could be ***register***, if we want to choose a simple, short name.

Any thoughts?

**Comment by ShermantheCreator** [comment]
Zach, I think register or registration is a good option. It is one word and we don't have to bother with hyphens or multiple words. What do you think?

**Comment by raghav4494** [comment]
Yes, people. It's my typo error. I will edit it. It should be registration or sign-up.

**Comment by zach27** [comment]
@ShermantheCreator, I like that motivation. How about **register**, since we are using **login** for another feature, and **login** is a verb?

**Comment by zach27** [comment]
Actually, it looks like "login" can be either a verb or a noun, but we are using it as a verb. :)
Any votes from @ashishkchaturvedi and @abjay?

**Comment by ShermantheCreator** [comment]
Yes, let's do Register. I will make changes to the dataflow document.

**Comment by abjay** [comment]
Hi Team,

Yes, register sounds good. It's a single word and clearly describes the
process.

Thanks,
Abhi

**Comment by zach27** [comment]
Sounds good, thanks, Russ. Let's each make changes to our artifacts if we've used the terms "account creation" or "sign-up" anywhere.

**Comment by ashishkchaturvedi** [comment]
Hi everyone,

To me register seems good....i think we reached a consensus

-Ashish
