### ISSUE TITLE
Peer review detailed requirements/design artifacts for sprint 3 features

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#40]
@abjay @ShermantheCreator Please review the [baselined requirements](https://github.com/CS506/fall2016-group1/blob/master/docs/sprint3/baselined-requirements.pdf) to see if you come up with any error conditions that I've missed. You can respond to this issue with any findings.

**Comment by zach27** [comment]
@abjay @ShermantheCreator I forgot that this task applies to ***all*** of sprint 3 requirements and design, not just for the "display drips" functionality, for which we have requirements right now. So you'll need to wait for the requirements/design artifacts from the other features.

**Also, when ready, do a quick scan through the *requirements*, but examine the *design artifacts* more carefully.** That's because the robustness of *design* is really what we're trying to improve here. Thanks!

**Comment by zach27** [comment]
@abjay @ShermantheCreator The three of us can look through the design artifacts now and see if we find any missing error conditions ("missing" as either in the requirements but not in the design, or completely missing in the requirements). Don't review your own artifacts...just everyone else's. We can respond with our findings here.

**Comment by zach27** [comment]
@raghav4494 I think you will need to modify the sprint 3 activity diagram for creating a drip to make it more robust. Notice here that it did not explicitly account for three error conditions: https://github.com/CS506/fall2016-group1/blob/master/docs/sprint2/design-robustness-measurements.md#create-drip. I know the diagram says we perform a check to see if the drip contents are "valid," but we need to explain what we mean by valid (using those error conditions at the link above). Does this make sense?

**Comment by abjay** [comment]
@zach27 I just reviewed the design artifacts. They look consistent with the baselined requirements. Also I don't think we are missing anything in the design.

**Comment by abjay** [comment]
@ShermantheCreator The logout state transition diagram and the activity diagram look good. Is there anything else we need to consider before measuring the design artifacts?

**Comment by zach27** [comment]
@abjay @ShermantheCreator I can't think of any other error conditions that are missing. I am finished with everything on my end for design. Anything else we're missing?

**Comment by abjay** [comment]
@zach27 I don't think anything is missing. We should proceed to measuring the designs.

**Comment by zach27** [comment]
Abhi and Russ and I have peer reviewed everything.
