### ISSUE TITLE
Peer review sprint 2 implementation flexibility measurements

### ISSUE THREAD

**Issue by abjay** [CS506/fall2016-group1#41]
@zach27 @ShermantheCreator can you guys please review the implementation flexibility measurements document for sprint 2 and see if its meaningful?
There are a lot of points in it that are more related to our opinions, and they are subjective. So please let me know if it makes sense within what we have discussed throughout sprint 2.

**Comment by zach27** [comment]
@abjay I think it looks fine overall, since the measurements will be somewhat subjective anyway. It will help if you are the one to always measure implementation flexibility to keep it consistently subjective. :)

**Comment by abjay** [comment]
Thanks @zach27 ! Yes, I will take up the task of measuring this metric in future sprints for the sake of consistency!
