### ISSUE TITLE
Add titles to design artifacts

### ISSUE THREAD

**Issue by zach27** [CS506/fall2016-group1#5]
After looking through the design artifacts, I think we should have titles on all of them so it is clear what they represent. The titles will basically be the same as the filename, telling the feature and kind of artifact. Let's remember this in the future.

Also, as you may have seen in the book, most of the artifacts are called *diagrams*, except for the data flow model, which is called a *model*. This is just a minor point, but let's make sure our naming reflects this.

**Comment by raghav4494** [comment]
Now I think every diagram is perfect with valid names and titles added. Both ppt and pdf files are present in their usual locations. Also, I have removed two files which were replicas of the activity and state diagram of register. i think we can close this issue. Comments?

**Comment by zach27** [comment]
Looks good. Thanks!
